// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/ddns-updater/internal/update (interfaces: DebugLogger)
//
// Generated by this command:
//
//	mockgen -destination=mock_update/logclient.go . DebugLogger
//

// Package mock_update is a generated GoMock package.
package mock_update

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDebugLogger is a mock of DebugLogger interface.
type MockDebugLogger struct {
	ctrl     *gomock.Controller
	recorder *MockDebugLoggerMockRecorder
	isgomock struct{}
}

// MockDebugLoggerMockRecorder is the mock recorder for MockDebugLogger.
type MockDebugLoggerMockRecorder struct {
	mock *MockDebugLogger
}

// NewMockDebugLogger creates a new mock instance.
func NewMockDebugLogger(ctrl *gomock.Controller) *MockDebugLogger {
	mock := &MockDebugLogger{ctrl: ctrl}
	mock.recorder = &MockDebugLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDebugLogger) EXPECT() *MockDebugLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockDebugLogger) Debug(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", s)
}

// Debug indicates an expected call of Debug.
func (mr *MockDebugLoggerMockRecorder) Debug(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockDebugLogger)(nil).Debug), s)
}
