// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/ddns-updater/pkg/publicip/dns (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mock_dns/client.go . Client
//

// Package mock_dns is a generated GoMock package.
package mock_dns

import (
	context "context"
	reflect "reflect"
	time "time"

	dns "github.com/miekg/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ExchangeContext mocks base method.
func (m_2 *MockClient) ExchangeContext(ctx context.Context, m *dns.Msg, a string) (*dns.Msg, time.Duration, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ExchangeContext", ctx, m, a)
	ret0, _ := ret[0].(*dns.Msg)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExchangeContext indicates an expected call of ExchangeContext.
func (mr *MockClientMockRecorder) ExchangeContext(ctx, m, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeContext", reflect.TypeOf((*MockClient)(nil).ExchangeContext), ctx, m, a)
}
