package errors

import "errors"

var (
	ErrAccountInactive           = errors.New("account is inactive")
	ErrAuth                      = errors.New("bad authentication")
	ErrBadRequest                = errors.New("bad request sent")
	ErrBannedAbuse               = errors.New("banned due to abuse")
	ErrBannedUserAgent           = errors.New("user agend is banned")
	ErrConflictingRecord         = errors.New("conflicting record")
	ErrDNSServerSide             = errors.New("server side DNS error")
	ErrDomainDisabled            = errors.New("record disabled")
	ErrDomainIDNotFound          = errors.New("ID not found in domain record")
	ErrDomainNotFound            = errors.New("domain not found")
	ErrFeatureUnavailable        = errors.New("feature is not available to the user")
	ErrHostnameNotExists         = errors.New("hostname does not exist")
	ErrHTTPStatusNotValid        = errors.New("HTTP status is not valid")
	ErrIPReceivedMalformed       = errors.New("malformed IP address received")
	ErrIPReceivedMismatch        = errors.New("mismatching IP address received")
	ErrIPSentMalformed           = errors.New("malformed IP address sent")
	ErrNoService                 = errors.New("no service")
	ErrPrivateIPSent             = errors.New("private IP cannot be routed")
	ErrReceivedNoIP              = errors.New("received no IP address in response")
	ErrReceivedNoResult          = errors.New("received no result in response")
	ErrRecordNotEditable         = errors.New("record is not editable")
	ErrRecordNotFound            = errors.New("record not found")
	ErrRecordResourceSetNotFound = errors.New("record resource set not found")
	ErrResponseTooShort          = errors.New("response is too short")
	ErrResultsCountReceived      = errors.New("wrong number of results received")
	ErrSessionIsEmpty            = errors.New("session received is empty")
	ErrSystemParamNotValid       = errors.New("system parameter is not valid")
	ErrUnknownResponse           = errors.New("unknown response received")
	ErrUnsuccessful              = errors.New("unsuccessful result")
	ErrZoneNotFound              = errors.New("zone not found")
)
