{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-updater-config
data:
  {{- with .Values.config }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
  {{- end -}}